// Fix: Created the missing constants.ts file to provide a sample course.
import { Course } from './types';

export const BRAMPTON_HEATH: Course = {
  id: 'brampton-heath-golf-centre',
  name: 'BRAMPTON HEATH GOLF CENTRE',
  slopeRating: 127,
  courseRating: 70.7,
  holes: [
    { hole: 1, par: 4, strokeIndex: 7 },
    { hole: 2, par: 4, strokeIndex: 15 },
    { hole: 3, par: 5, strokeIndex: 1 },
    { hole: 4, par: 4, strokeIndex: 3 },
    { hole: 5, par: 3, strokeIndex: 11 },
    { hole: 6, par: 5, strokeIndex: 13 },
    { hole: 7, par: 3, strokeIndex: 17 },
    { hole: 8, par: 4, strokeIndex: 9 },
    { hole: 9, par: 4, strokeIndex: 5 },
    { hole: 10, par: 5, strokeIndex: 12 },
    { hole: 11, par: 5, strokeIndex: 16 },
    { hole: 12, par: 3, strokeIndex: 8 },
    { hole: 13, par: 4, strokeIndex: 18 },
    { hole: 14, par: 4, strokeIndex: 4 },
    { hole: 15, par: 4, strokeIndex: 2 },
    { hole: 16, par: 3, strokeIndex: 14 },
    { hole: 17, par: 4, strokeIndex: 6 },
    { hole: 18, par: 4, strokeIndex: 10 },
  ],
  teeSets: [
    {
      name: 'White',
      slopeRating: 130,
      courseRating: 72.7,
      holes: [
        { hole: 1, par: 4, strokeIndex: 7 },
        { hole: 2, par: 4, strokeIndex: 15 },
        { hole: 3, par: 5, strokeIndex: 1 },
        { hole: 4, par: 4, strokeIndex: 3 },
        { hole: 5, par: 3, strokeIndex: 11 },
        { hole: 6, par: 5, strokeIndex: 13 },
        { hole: 7, par: 3, strokeIndex: 17 },
        { hole: 8, par: 4, strokeIndex: 9 },
        { hole: 9, par: 4, strokeIndex: 5 },
        { hole: 10, par: 5, strokeIndex: 12 },
        { hole: 11, par: 5, strokeIndex: 16 },
        { hole: 12, par: 3, strokeIndex: 8 },
        { hole: 13, par: 4, strokeIndex: 18 },
        { hole: 14, par: 4, strokeIndex: 4 },
        { hole: 15, par: 4, strokeIndex: 2 },
        { hole: 16, par: 3, strokeIndex: 14 },
        { hole: 17, par: 4, strokeIndex: 6 },
        { hole: 18, par: 4, strokeIndex: 10 },
      ]
    },
    {
      name: 'Yellow',
      slopeRating: 127,
      courseRating: 70.7,
      holes: [
        { hole: 1, par: 4, strokeIndex: 7 },
        { hole: 2, par: 4, strokeIndex: 15 },
        { hole: 3, par: 5, strokeIndex: 1 },
        { hole: 4, par: 4, strokeIndex: 3 },
        { hole: 5, par: 3, strokeIndex: 11 },
        { hole: 6, par: 5, strokeIndex: 13 },
        { hole: 7, par: 3, strokeIndex: 17 },
        { hole: 8, par: 4, strokeIndex: 9 },
        { hole: 9, par: 4, strokeIndex: 5 },
        { hole: 10, par: 5, strokeIndex: 12 },
        { hole: 11, par: 5, strokeIndex: 16 },
        { hole: 12, par: 3, strokeIndex: 8 },
        { hole: 13, par: 4, strokeIndex: 18 },
        { hole: 14, par: 4, strokeIndex: 4 },
        { hole: 15, par: 4, strokeIndex: 2 },
        { hole: 16, par: 3, strokeIndex: 14 },
        { hole: 17, par: 4, strokeIndex: 6 },
        { hole: 18, par: 4, strokeIndex: 10 },
      ]
    },
    {
      name: 'Green',
      slopeRating: 119,
      courseRating: 68.3,
      holes: [
        { hole: 1, par: 4, strokeIndex: 7 },
        { hole: 2, par: 4, strokeIndex: 15 },
        { hole: 3, par: 5, strokeIndex: 1 },
        { hole: 4, par: 4, strokeIndex: 3 },
        { hole: 5, par: 3, strokeIndex: 11 },
        { hole: 6, par: 5, strokeIndex: 13 },
        { hole: 7, par: 3, strokeIndex: 17 },
        { hole: 8, par: 4, strokeIndex: 9 },
        { hole: 9, par: 4, strokeIndex: 5 },
        { hole: 10, par: 5, strokeIndex: 12 },
        { hole: 11, par: 5, strokeIndex: 16 },
        { hole: 12, par: 3, strokeIndex: 8 },
        { hole: 13, par: 4, strokeIndex: 18 },
        { hole: 14, par: 4, strokeIndex: 4 },
        { hole: 15, par: 4, strokeIndex: 2 },
        { hole: 16, par: 3, strokeIndex: 14 },
        { hole: 17, par: 4, strokeIndex: 6 },
        { hole: 18, par: 4, strokeIndex: 10 },
      ]
    },
    {
      name: 'Red',
      slopeRating: 126,
      courseRating: 72.4,
      holes: [
        { hole: 1, par: 4, strokeIndex: 7 },
        { hole: 2, par: 4, strokeIndex: 11 },
        { hole: 3, par: 5, strokeIndex: 3 },
        { hole: 4, par: 4, strokeIndex: 5 },
        { hole: 5, par: 3, strokeIndex: 15 },
        { hole: 6, par: 5, strokeIndex: 1 },
        { hole: 7, par: 3, strokeIndex: 17 },
        { hole: 8, par: 4, strokeIndex: 9 },
        { hole: 9, par: 4, strokeIndex: 13 },
        { hole: 10, par: 5, strokeIndex: 8 },
        { hole: 11, par: 5, strokeIndex: 14 },
        { hole: 12, par: 3, strokeIndex: 16 },
        { hole: 13, par: 4, strokeIndex: 6 },
        { hole: 14, par: 4, strokeIndex: 12 },
        { hole: 15, par: 4, strokeIndex: 2 },
        { hole: 16, par: 3, strokeIndex: 18 },
        { hole: 17, par: 4, strokeIndex: 4 },
        { hole: 18, par: 4, strokeIndex: 10 },
      ]
    }
  ],
};

export const SAMPLE_COURSE = BRAMPTON_HEATH;

